### PR TITLE
SupervisordConfig: added supervisord config

### PR DESCRIPTION
**Pull request by faisalraja**

### CODE REVIEW

**Comment by dsmurl** [comment]
I'm excited to have the supervisor rolling.  This is one of the advanced features I wanted.  I'm not familiar with this enough to know when to merge it.  Maybe a briefing on it or something.

**Comment by faisalraja** [comment]
Basically run this command to control the app.

 # to start it (it's important that this is ran in the project root)
 supervisord -c supervisord.conf

 # to control it (stop supervisord)
 supervisorctl shutdown

 # restart the webserver
 supervisorctl restart all (or specific "restart syscontroller4")

you can reload config, restart supervisord etc use supervisorctl help for more commands

**Comment by dsmurl** [comment]
Cool.  Does this run the process as the root level.  I think the process needs the root level to get the pin readings.  The pins on the BeagleBone are in the /dev folder and are virtual file descriptors owned by root only.  I typically have to do something like  

sudo python wsgi.py
   or
sudo python wsgi.py &                         // to run in background

**Comment by faisalraja** [comment]
You'd have to run the supervisord -c supervisord.conf as root and everything it runs will be root unless specified in config.

**Comment by dsmurl** [comment]
cool.  It would be nice to setup it up on boot.  I'll look into it.

**Comment by dsmurl** [comment]
So you think this is ready to merge?  I'll merge it now if it's complete and check into it's workings later.

**Comment by faisalraja** [comment]
If you run it successfully with that command it should be fine. You might have file path difference but I think the paths are common. You can check and run it on beaglebone.

**Pull request merged**
